apiVersion: v1
entries:
  smtp-relay:
  - apiVersion: v2
    appVersion: v1.1.4
    created: "2025-10-15T17:51:04.797395812Z"
    description: A Helm chart for Kubernetes
    digest: ce367fbbaaf36e7b7e50b0ba210cb07ebffae991c678d378b620f313196fec5f
    icon: https://www.smtp2graph.com/media/logo.png
    name: smtp-relay
    type: application
    urls:
    - https://github.com/adamcubel/smtp2graph-helm-chart/releases/download/v0.1.3/smtp-relay-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: v1.1.4
    created: "2025-10-15T17:51:04.796825182Z"
    description: A Helm chart for Kubernetes
    digest: 95822fca18d59df142db20b3a6665db32f34decd539d7f34a376533020abc3eb
    icon: https://www.smtp2graph.com/media/logo.png
    name: smtp-relay
    type: application
    urls:
    - https://github.com/adamcubel/smtp2graph-helm-chart/releases/download/v0.1.3/smtp-relay-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: v1.1.4
    created: "2025-10-15T17:51:04.796215859Z"
    description: A Helm chart for Kubernetes
    digest: 1d6bfd32b1847e962cc7432b93ec5a1cb05b2cc1f5e42310cd1f3636098d3617
    icon: https://www.smtp2graph.com/media/logo.png
    name: smtp-relay
    type: application
    urls:
    - https://github.com/adamcubel/smtp2graph-helm-chart/releases/download/v0.1.3/smtp-relay-0.1.1.tgz
    version: 0.1.1
generated: "2025-10-15T17:51:04.795466263Z"
