# Example: Azure App Registration Secret
# This secret contains the Azure App Registration details needed for SMTP2Graph
# to authenticate with Microsoft Graph API.

apiVersion: v1
kind: Secret
metadata:
  name: smtp2graph-appreg
  namespace: default  # Change to your namespace
type: Opaque
stringData:
  # Azure tenant (name or GUID)
  # Example: "contoso" or "12345678-1234-1234-1234-123456789abc"
  tenant: "your-tenant-name-or-id"

  # Azure App Registration (Client) ID
  appId: "01234567-89ab-cdef-0123-456789abcdef"

  # Certificate thumbprint (SHA-1 fingerprint)
  certificateThumbprint: "0123456789ABCDEF0123456789ABCDEF01234567"

  # Private key in PEM format
  # Replace with your actual private key content
  certificateKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC...
    ...your private key content here...
    -----END PRIVATE KEY-----

  # Optional: Client secret (use instead of certificate)
  # Uncomment if using client secret authentication instead of certificate
  # clientSecret: "your-client-secret-value"

  # Optional: Force sending from a specific mailbox
  # forceMailbox: "smtp2graph@example.com"

# ---
# Alternative: Using certificate files
# If you have the certificate in a file, you can create the secret from files:
#
# kubectl create secret generic smtp2graph-appreg \
#   --from-literal=tenant=contoso \
#   --from-literal=appId=01234567-89ab-cdef-0123-456789abcdef \
#   --from-literal=certificateThumbprint=0123456789ABCDEF0123456789ABCDEF01234567 \
#   --from-file=certificateKey=./client.key
